### ISSUE TITLE
The LinkedIn link isn't actually me

### ISSUE THREAD

**Issue by Zhuinden** [ibrajix/AndroidDevelopers#1]
https://www.linkedin.com/in/gabor-varadi-04274219/

This is a different Gabor Varadi, i personally don't really use linkedIn 😅 

I have an account but there's nothing on it to see. I only have it because it shares login with Slideshare.

**Comment by ibrajix** [comment]
> https://www.linkedin.com/in/gabor-varadi-04274219/
> 
> This is a different Gabor Varadi, i personally don't really use linkedIn 😅
> 
> I have an account but there's nothing on it to see. I only have it because it shares login with Slideshare.

Oh wow.. To think that the person is also a "java" developer. 😮 

Sorry about that, I have removed the LinkedIn link.
